### ISSUE TITLE
Failed verification because kubeconform could not find local schema

### ISSUE THREAD

**Issue by maowerner** [yannh/kubeconform#115]
I am trying to validate Argo-Workflows with kubeconform. Unfortunately no matter what I always get an error because kubeconform `could not find schema`.

I specifically try to validate the `CronWorkflow` and `WorkflowTemplate` in version `v1alpha1`. They have an openapi definition which I parsed with `openapi2jsonschema`
```
openapi2jsonschema https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json 
```

This creates files `schemas/cronworkflow.json` and `schemas/workflowtemplate.json` with the correct schemas.

From the documentation I inferred that it should just work by specifying the format with a  Go templated string that indicates how to search for JSON schemas
```
❯ kubeconform -schema-location default -schema-location 'schemas/{{ .ResourceKind }}.json' -summary --verbose -output json resources/
{
  "resources": [
    {
      "filename": "stdin",
      "kind": "WorkflowTemplate",
      "name": "redacted",
      "version": "argoproj.io/v1alpha1",
      "status": "statusError",
      "msg": "could not find schema for WorkflowTemplate"
    },
    {
      "filename": "stdin",
      "kind": "CronWorkflow",
      "name": "redacted",
      "version": "argoproj.io/v1alpha1",
      "status": "statusError",
      "msg": "could not find schema for CronWorkflow"
    }
  ],
  "summary": {
    "valid": 0,
    "invalid": 0,
    "errors": 2,
    "skipped": 0
  }
}
```

Without the verbosity it only says
```
could not find schema for WorkflowTemplate
could not find schema for CronWorkflow
```

I actually managed to validate my files with `kubeval` by renaming them to `schemas/master-standalone/cronworkflow-argoproj-v1alpha1.json` and schemas/master-standalone/workflowtemplate-argoproj-v1alpha1.json` and running with 
```
kubeval --additional-schema-locations file://./schemas
```
So I am very certain, that the content of the files themselves is fine. 

However the renaming is not very maintainable and I would like to use kubeconform here. Curiously I still get the same error when I shun the templated string and instead use the naming scheme that worked in kubeval, 

I also read all the help pages but can not find an option that further increases the verbosity level. Thus I did not manage to analyze the error deeper than this. I essentially checked all thinkable combinations of `ResourceKind` and `KindSuffix` but to no avail.

It is also not an option to extract the apiVersion as well because I get an error
```
❯ openapi2jsonschema https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json  --kubernetes
Downloading schema
Parsing schema
Generating shared definitions
Generating individual schemas
Traceback (most recent call last):
  File "/home/maow/.asdf/installs/python/3.9.10/bin/openapi2jsonschema", line 8, in <module>
    sys.exit(default())
  File "/home/maow/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/maow/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/maow/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/maow/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/maow/.asdf/installs/python/3.9.10/lib/python3.9/site-packages/openapi2jsonschema/command.py", line 132, in default
    group = title.split(".")[-3].lower()
IndexError: list index out of range
```
Presumably this is cause by an incomplete naming in the openapi specification. This is something that I encountered for other projects as well and I am not sure who's fault this is. I assume the standard is either not restrictive enough not being followed consequently.

I would be really thankful for suggestions how to specify the correct schema location, modify the openapi extraction or even just make kubeconform print the path it searched in so that I can out what is not working here.

**Comment by eyarz** [comment]
works on my machine 🤔
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/19731161/172872477-f6290230-cc9c-4118-b327-5cd5e8103cbc.png">

can you try to use the schemas from here?
https://github.com/datreeio/CRDs-catalog/tree/main/argo

**Comment by maowerner** [comment]
I was looking for exactly such a repo as well but it did not come up in my searches. With these schema definitions it works out of the box. I will investigate the difference a bit, but these solves my ticket.

I noticed a typo `deafult` - `default` in your command and instead of downloading I used the repo directly
```
☸ prod-k8s-kaj (prod-kafka) ❯ cat .templates/prod/meta-apps-kaj | kubeconform -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argo/{{ .ResourceKind }}_v1alpha1.json' -summary --verbose 
stdin - Application one is valid
stdin - Application two is valid
stdin - Application three is valid
stdin - Application four is valid
stdin - Application five is invalid: For field spec: Additional property syncPlicy is not allowed
stdin - Application six is valid
stdin - Application seven is valid
stdin - Application eight is valid
stdin - Application nine is valid
stdin - Application ten is valid
stdin - Application eleven is valid
stdin - Application twelve is valid
stdin - Application thirteen is valid
stdin - Application fourteen is valid
Summary: 14 resources found parsing stdin - Valid: 13, Invalid: 1, Errors: 0, Skipped: 0
```

Thank you very much.
