### ISSUE TITLE
Multiple schema locations

### ISSUE THREAD

**Issue by avencl** [yannh/kubeconform#118]
Hi, I was trying to use kubeconform to validate some resources that are supported and some that would be CustomResources. And everything works perfectly when i pass `-schema-location default` and `-schema-location <pathToJson1>`. But when i try to do something like this `-schema-location default -schema-location <pathToJson1> -schema-location <pathToJson2>` it only looks at first schema passed and when it comes to some yaml that 2nd schema describes i get message "It has to be of kind <first schema kind>". Am I maybe doing something wrong with passing flags, or is this kind of behaviour just not supported?

**Comment by avencl** [comment]
I managed to go around it. 

The error was when i tried to use command like this:
`kubeconform mapping.yaml -schema-location schema/hydra.json -schema-location schema/mapping.json` i would get this error: `mapping.yaml - Mapping api failed validation: could not find schema for Mapping`

But when i ordered `schema-location` differently like this : `kubeconform mapping.yaml -schema-location schema/mapping.json -schema-location schema/hydra.json` everything worked fine, but when i tried to evaluate hydra files he would say they must have `kind: Mapping`

I think I located potential error in your code that when there are more -schema-location it only looks at first and throws error if that fails: https://github.com/yannh/kubeconform/blob/7bf1e01decc7e16c3a2d2388515e374d9629fd79/pkg/registry/local.go#L23

The work around was (per documentation) to use command like this: `kubeconform mapping.yaml -schema-location schema/{{. .ResourceKind}}.json` and now everything works as intended.

**Comment by yannh** [comment]
Hi @avencl , sorry for the late reply - yes, this is the intended behaviour. Sorry if the documentation was not clear!
