### ISSUE TITLE
Improvements in License File

### ISSUE THREAD

**Issue by amar-chand** [yannh/kubeconform#146]
Hey @yannh,

Greetings. Our team is trying to import and use Kubeconform for some validation part in our codebase. However, the Apache License file that has been added to this repo is not a proper Apache License file, due to which our code pipelines are not able to understand the license and checks are failing. We are unable to move forward until the license file is proper. Could you please add an appropriate `Apache License 2.0` License file? It would be super helpful.

Thank you so much.

P.S.: [Here](https://github.com/argoproj/argo-workflows/blob/master/LICENSE) is a link to sample Apache License 2.0 license file for your reference. I hope it would help. In case of any query, please do let me know.

**Comment by yannh** [comment]
Fixed :heavy_check_mark:
