### ISSUE TITLE
Using --schema-location still tries to fetch `$ref` resources over the network

### ISSUE THREAD

**Issue by yabberyabber** [yannh/kubeconform#151]
I would like to run kubeconform without network access.  It looks like the `--schema-location` flag gets me most of the way there - I can pre-download the github.com/yannh/kubernetes-json-schema repository and reference my local clone. However, I see that inside the type definitions, there are links to other resources in the repository that come from the web.

Is there a way I can run this without web access? It seems like the kubernetes-json-schema repository has the content I need, I just need some way to tell kubeconform that when it follows the $ref entries that point at the web, it actually needs to check locally first.

**Comment by eyarz** [comment]
point the `--schema-location` to use the `local` (suffix) schemas:
https://github.com/yannh/kubernetes-json-schema/blob/master/build.sh#L9

**Comment by yabberyabber** [comment]
Thanks so much! That's exactly what I was looking for :)
