### ISSUE TITLE
Error when running it as a Docker container

### ISSUE THREAD

**Issue by GuillermoContrerasP** [yannh/kubeconform#154]
Hello,

I'm trying to running it as a Docker container with the following command:

`docker run -t -i --rm --init ghcr.io/yannh/kubeconform examples/cassandra/cassandra-service.yaml`

However, I'm getting the following error:
`examples/cassandra/cassandra-service.yaml - failed validation: lstat examples/cassandra/cassandra-service.yaml: no such file or directory`

The file does exists, but I cannot get this working. I tried also using a path rather than a single file and it fails as well.

The version used is the following one:
docker run -t -i --rm --init ghcr.io/yannh/kubeconform -v
**v0.5.0**

Please advice if there is a way to make it work with Docker. 
Thanks in advance

**Comment by Hongbo-Miao** [comment]
[Here](https://github.com/Hongbo-Miao/hongbomiao.com/blob/b454498061db43603555df8d9bd9313f9cba4bd8/.github/workflows/test.yml#L203-L215) is how I use.

Assume you have a folder `/kubernetes`, then you can mount inside to the container by running:

```sh
docker run \
  --rm \
  --volume=`pwd`/kubernetes:/kubernetes \
  ghcr.io/yannh/kubeconform:latest \
    -kubernetes-version=1.26.0 \
    kubernetes/
```

**Comment by GuillermoContrerasP** [comment]
Hello @Hongbo-Miao 
Thanks a lot for the example command. I was able to make it work on my environment.

Cheers
