### ISSUE TITLE
Suggestion: support to ignore some particular issues

### ISSUE THREAD

**Issue by LinuxSuRen** [yannh/kubeconform#162]
I'm  trying to use kubeconform to check [Argo](https://github.com/argoproj/argo-workflows/) workflow YAML files. The following error report is totally correct. But actually the `template` field is optional. This might be a potential issue of Argo workflows. But it would be great if we could ignore some issues like this before the potential issue have any progress.

```json
    {
      "filename": ".workflows/workflow.yaml",
      "kind": "WorkflowTemplate",
      "name": "workflow-infra",
      "version": "argoproj.io/v1alpha1",
      "status": "statusInvalid",
      "msg": "For field spec.hooks.all: template is required - For field spec.hooks.exit: template is required"
    }
```

**Comment by yannh** [comment]
Hi  @LinuxSuRen , is it possible that the JSON schema specified that the field is actually required? I am  not sure I would implement this as a feature...

**Comment by LinuxSuRen** [comment]
I'm thinking about how to ignore some particular issues. For example, we could ignore the issues by some keywords.

**Comment by yannh** [comment]
@LinuxSuRen I will close this ticket, as I am not sure I would implement this directly in Kubeconform. I would recommend manipulating the JSON output, with jq or a scripting language - that might allow you to filter out errors. Not perfect I guess, but might be a reasonable workaround :bow:
