### ISSUE TITLE
Suggestion: quicker GitHub Action

### ISSUE THREAD

**Issue by hermanbanken** [yannh/kubeconform#175]
I was inspired by golangci-lint through their ease of use. I noticed the readme mentions running kubeconform using Docker in using GH_TOKEN, but with an action such as https://github.com/hermanbanken/kubeconform-action it is even easier & less fault tolerant to install kubeconform (no GH_TOKEN needed).

Feel free to integrate https://github.com/hermanbanken/kubeconform-action.

**Comment by hermanbanken** [comment]
Alternative is mentioning a completely generic action such as https://github.com/jaxxstorm/action-install-gh-release.

**Comment by yannh** [comment]
Hi @hermanbanken ! Thank you for making a JS action variant for Github actions! Could you expand on what makes it easier to use? I remember looking at these JS actions and wondering what the benefit was, it seemed like it requires you to write a fair bit of js wiring code... is it faster? easier to use? The GH_TOKEN you don't need to generate, it is automatically provided by Github actions, do you see this as problematic? Thanks!

**Comment by hermanbanken** [comment]
You don't need to send a GH_TOKEN to any action this way. So it is completely unauthenticated process, leaving you with no risk the action performs any API requests with said token.

It is also ridiculously fast. 0.1s-0.3s by my measures (see GH Action tab of my action).

I'm not sure how long the Docker login & image download takes, but it seems more cumbersome than simply having the tool available in the runner. You might want to combine the outputs or in other ways do some bash scripting, which is less then trivial with a Docker action.

**Comment by hermanbanken** [comment]
I had a caching bug in my composite action, but the other one I mentioned is doing that correctly in a generic fashion.

**Comment by hermanbanken** [comment]
Note I'm a bit paranoid about GH Actions because they make it impossible to vet the source code your running except when pinning to a commit. Any malicious person owning an action could update an action used in millions of repos to run different code by recreating the tag.

Having all actions pinned like this, it is much more convenient to only focus on JS actions and not have the trouble of also pinning Docker versions.

(Checking checksums would also be on my wishlist, if it isn't supported already.)

**Comment by yannh** [comment]
Ah - yes that's fair, I understand. I wonder if the token is still absolutely necessary to pull the image tbh :thinking:

**Comment by rouke-broersma** [comment]
Why would you need a token to pull public images from github container registry? Try `docker run ghcr.io/yannh/kubeconform` locally, you'll see pulling works fine.

**Comment by hermanbanken** [comment]
Sorry, I was basing that comment on old information. I looked it up, this changed on June 21st of 2021.
https://github.blog/2021-06-21-github-packages-container-registry-generally-available/

**Comment by yannh** [comment]
@hermanbanken > I would close this issue, since the main problem about using the Github Token seems to be solved. The Kubeconform image should be pretty small, so I am not massively concerned by the duration? The fact that I do not have to maintain any code for a Docker action seems to be a worthy tradeoff :grimacing: 
Best,
Yann
