### ISSUE TITLE
request/limit invalid values pass kubeconform

### ISSUE THREAD

**Issue by zapman449** [yannh/kubeconform#181]
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: kubernetes/pause
        resources:
          requests:
            cpu: "100Mi"                      # invalid. should be `m`
            memory: "128Mi"
          limits:
            cpu: "500Mi"                      # invalid. should be `m`
            memory: "2560Mi"
        ports:
          - name: http
            containerPort: 8080
```

This should fail the test because the values for `cpu` are invalid.

I suspect this might be similar to #132 but wanted to validate.

**Comment by eyarz** [comment]
yes, this is not part of the schema definition.
there are many other validations that are not included (you can find more info [here](https://github.com/yannh/kubeconform/issues/178))

**Comment by yannh** [comment]
Closing as indeed - this can unfortunately not be validated using the JSON schema validation Kubeconform is doing, as suggested by @eyarz .
