### ISSUE TITLE
Consider crd2jsonschema

### ISSUE THREAD

**Issue by tricktron** [yannh/kubeconform#182]
Hi there,

I am the author of [crd2jsonschema](https://github.com/tricktron/crd2jsonschema) and this may be a good fit for an alternative to your openapi2jsonschema.py script.

crd2jsonschema uses [openapi-schema-to-json-schema](https://github.com/openapi-contrib/openapi-schema-to-json-schema) library under the hood which converts openAPI v3 to jsonschema draft 4. See also https://github.com/datreeio/CRDs-catalog/pull/142#issuecomment-1476277143 for more info.

**Comment by tricktron** [comment]
Yeah, I have seen your https://github.com/yannh/openapi2jsonschema script as well. What do you think about an incremental approach: First check and see if all works with crds and if all is well I think about extending it to support the kubernetes json schema use case.

**Comment by yannh** [comment]
@tricktron I'll be closing this issue, but thanks for pointing this out. I am likely to ask people encountering issues to give it a shot and provide feedback :bow:   Thanks :1st_place_medal:

**Comment by eloo-abi** [comment]
hi i have tested your js script and it produces the same output as the script in this repository but add the dependency to the node_module

so right now i do not see any benefit here
