### ISSUE TITLE
Version information rendered by `-v` flag is off

### ISSUE THREAD

**Issue by bmuschko** [yannh/kubeconform#185]
I installed the latest version of kubeconform from Homebrew. Rendering the version information points to `development`. Shouldn't this render the latest final version e.g. `v0.6.1`?

```
$ kubeconform -v

development
```

**Comment by yannh** [comment]
It should, thanks for noticing! It looks like I broke this 2 years ago when refactoring the CI pipeline...

**Comment by bmuschko** [comment]
Creating the binary locally works fine with the GoReleaser binary 1.16.2. The generated binary indicates the correct version.

```
$ git checkout v0.6.1
$ goreleaser build
$ dist/kubeconform_darwin_amd64_v1/kubeconform -v
v0.6.1
```

Is there maybe something off with running GoReleaser in a Docker container [here](https://github.com/yannh/kubeconform/blob/master/Makefile#L38)?

**Comment by yannh** [comment]
@bmuschko  It looks like Homebrew recompiles kubeconform from sources https://github.com/Homebrew/homebrew-core/blob/5bfcb5ec2b72344e8bb82d173ad09c737ace9ce7/Formula/kubeconform.rb#L22  

I'd suggest opening a bug against homebrew-core - the build command line would need to include -X main.version=0.6.1
