### ISSUE TITLE
Multi schema-location doesn't work properly

### ISSUE THREAD

**Issue by hosein-yousefii** [yannh/kubeconform#191]
Hello,

I faced an issue today by using multi schema-location, Kubeconform just check the code against the first schema-location.

![kubeconform](https://user-images.githubusercontent.com/78673737/231451813-d0e48652-baa5-4c90-a14c-7f4ca27705e7.PNG)

In the first command the servicemonitor came first so it just validate it.
In the second command the kafkaconnector came first so it just validate it.

so when you have multi CRDs schema you would face a problem.

**Comment by eyarz** [comment]
this is the expected behavior.
you're "forcing" kubeconform to validate `servicemonitor` and `kafkaconnector` against the same schema.
to validate both resources, replace the multiple schema location with this:
```
kubeconform --schema-location '{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' 
```

**Comment by hosein-yousefii** [comment]
Thanks for that, I just realized how it works.
