### ISSUE TITLE
better error message

### ISSUE THREAD

**Issue by DanielYWoo** [yannh/kubeconform#207]
The error message can be better. e.g., for the YAML below
```
~                              | 24       source:
~                              | 25         repoURL: https://somerepo
~                              | 26         targetRevision: main
~                              | 27         path: ./
~                              | 28         helm:
~                              | 29           releaseName: plt
~                              | 30           valueFiles:
~                              | 31             - overrides/values.yaml # default
~                              | 32             - overrides/{{region}}/{{env}}/values.yaml # per env override
~                              | 33           parameters: # values that can be inferred from appset
~                              | 34             - name: "consul.global.datacenter"
~                              | 35               value: {{region}}-{{env}}

```
kubeconform tells me something is wrong, but ain't tell me what is wrong.
```
failed validation: error unmarshalling resource: error converting YAML to JSON: yaml: line 34: did not find expected key
```

**Comment by DanielYWoo** [comment]
I fixed it by extra double quotes around the literals. This code snippet is from an ArgoCD application set, I cannot find a  way to render it locally without ArgoCD, so I have to pass it to kubeconform. ;-)

**Comment by DanielYWoo** [comment]
Yes, I figured it out, but, is it possible to print a better error message by any chance?

**Comment by eyarz** [comment]
sure!
It's an open-source project, so you or someone from the community is more than welcome to contribute a PR

**Comment by yannh** [comment]
Hi @DanielYWoo , it looks like the error comes from the Go YAML parser Kubeconform uses https://github.com/kubernetes-sigs/yaml  (the one Kubernetes uses too, I believe) which relies on https://github.com/go-yaml/yaml  - which throws this error.  A nicer error would be good, but it requires fixing a number of external dependencies which falls a bit outside of the time I can allocate to this project. Sorry :(
