### ISSUE TITLE
Was 0.6.2 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [yannh/kubeconform#212]
The update Homebrew did to the package in May has a different hash than the current 0.6.2 release. 
Because the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do I just want to check if this was retagged or compromised.

**Comment by yannh** [comment]
Hi @SMillerDev , :facepalm: yes it has been, sorry, I realised there was a tag but no release and pushed again :/ So - no compromise, and I will be sure to not do that again. Do you need a 0.6.3 to release on Homebrew?

**Comment by SMillerDev** [comment]
0.6.3 release would be nice, but I can also just update the hash.

**Comment by yannh** [comment]
If updating the hash is an option :bow:  It would prevent a release with no changes. Because there were no packages / containers created I thought noone was using this , sorry :bow:
