### ISSUE TITLE
Failure building with go 1.21

### ISSUE THREAD

**Issue by rombert** [yannh/kubeconform#229]
Hi,

I am packaging `kubeconform` on the openSUSE build service so that it's available out-of-the-box for SUSE-based distributions. The Tumbleweed flavour of openSUSE recently upgraded to Go 1.21, and this caused the kubeconform build to fail with

```
/usr/lib64/go/1.21/src/cmd/vendor/github.com/google/pprof/internal/driver/webhtml.go:26:12: pattern html: no matching files found
```

This failure is present with the latest 0.6.3 version. It would be great if you could provide an update/patch that would fix Go 1.21 compatibility.

Thanks!

**Comment by yannh** [comment]
Hi @rombert ! Thanks a LOT for the packaging effort :heart:  I have a 1.21 branch among some other updates here, I couldn't reproduce the issue https://github.com/yannh/kubeconform/pull/231  - are you still hitting it?

**Comment by rombert** [comment]
HI @yannh . In the meantime I have a received a reply from the openSUSE Go maintainers saying that this may be an issue specific to openSUSE and not something that needs fixing on the kubeconform side.

> This may be a packaging issue specific to openSUSE and once we understand more the kubeconform upstream issue can likely be closed.

https://lists.opensuse.org/archives/list/packaging@lists.opensuse.org/thread/W7B7GJUSPOYVGSCDLG3NORCXX764TKF6/

I did not close this issue yet since I did not get that confirmation, but it's likely that no fix is going to be needed in this project.

**Comment by rombert** [comment]
@yannh - I have confirmation that the openSUSE build has been fixed, so closing this. Sorry for the noise.
