### ISSUE TITLE
New release with latest Go version?

### ISSUE THREAD

**Issue by lboynton** [yannh/kubeconform#238]
Current release of kubeconform is using golang version 1.19.1 which is being flagged as having security vulnerabilities in various docker image scanning tools.

```
go version kubeconform 
kubeconform: go1.19.1
```

Is it possible to release a new version with a latest version of Go?

**Comment by yannh** [comment]
Sure! I ll do this as soon as I find some time. No promises, if anyone makes a PR before I do I would merge it :)

**Comment by yannh** [comment]
Done in https://github.com/yannh/kubeconform/pull/245  I ll cut a release soon
