### ISSUE TITLE
GitHub Action that downloads, installs, and adds CLI tool to PATH

### ISSUE THREAD

**Issue by bmuschko** [yannh/kubeconform#241]
From your [documentation](https://github.com/yannh/kubeconform#github-workflow), it seems that the recommended way to run Kubeconform in GitHub Actions is the form of a container. I created and published the GitHub Action [setup-kubeconform](https://github.com/bmuschko/setup-kubeconform) that installs the CLI tools with the correct distribution. The setup looks more straight-forward to me. Do you think it would be helpful to add or even replace your recommendation in the README page?

**Comment by yannh** [comment]
Hi @bmuschko , thanks for your contribution! Seems interesting, I'll give it a proper review in the coming days :bow:

**Comment by joebowbeer** [comment]
By the way, kubeconform and many other kube tools can be added by arkade action

https://github.com/alexellis/arkade/pull/784

**Comment by bmuschko** [comment]
@yannh Do you have any feedback on this?
