### ISSUE TITLE
Schema for v1.26.10 is missing

### ISSUE THREAD

**Issue by jrsmroz** [yannh/kubeconform#242]
The schema for v1.26.10 is missing. Is it intended?

**Comment by yannh** [comment]
Should be there https://github.com/yannh/kubernetes-json-schema/tree/master/v1.26.10  ? Does it work with other versions? :bow:

**Comment by jrsmroz** [comment]
Apparently I'm blind, forgot to drink my coffee today and for sure forgot how github sorts folder lexicographically.  🙇
