### ISSUE TITLE
Bug: Junit output shows top-level error count, but not error-count within a test suite

### ISSUE THREAD

**Issue by jcmcken** [yannh/kubeconform#246]
E.g. it shows output like:

```xml
<testsuites name="kubeconform" ... errors="1">
  <testsuite ... errors="0">
    <testcase name="foo" ...>
      <error message="could not find schema for Ingress"></error>
    </testcase>
  </testsuite>
</testsuites>
```

The individual test case sees the error message, but it's not counted in the test suite summary (``errors="0"``), and it is counted at the very top level (``errors="1"``).

Running kubeconform like this:

```
kubeconform -schema-location /path/to/local/dir -strict -summary -output junit -verbose /path/to/dir
```

**Comment by yannh** [comment]
Hi @jcmcken , you are correct. I have opened a branch that should fix the behaviour. Expect a merge and a release in the next few weeks. Thanks a lot for reporting the issue!
