### ISSUE TITLE
Question: Can kubeconform report deprecated APIs?

### ISSUE THREAD

**Issue by joebowbeer** [yannh/kubeconform#248]
Given what kubeconform does, it seems natural to ask if it can also detect deprecated APIs, before they are removed? But a quick search didn't return any results.

Can kubeconform do this? Or is another tool such as kubent or pluto needed for that?

**Comment by yannh** [comment]
@joebowbeer it can not directly do that, but you can always check your manifests against newer versions of Kubernetes schemas.. That is, if you're running 1.26, you can test against 1.27 and 1.28, which should give you a good heads up of when some of your manifests won ´t be compatible anymore?

**Comment by yannh** [comment]
Closing - my current recommendation would be the one above :point_up: There might be other tools that take a different approach though :bow:
