### ISSUE TITLE
Dockerfile has deprecated `MAINTAINER` label

### ISSUE THREAD

**Issue by Stringls** [yannh/kubeconform#266]
Hi! `MAINTAINER` Label [has been deprecated](https://docs.docker.com/reference/dockerfile/#maintainer-deprecated) recently and replaced with `org.opencontainers.image.authors` that you already use in your [Dockerfiles](https://github.com/yannh/kubeconform/blob/master/Dockerfile#L5).

I suggest removing the label.

If you don't mind, I'd like to do these changes and open a new PR.

**Comment by yannh** [comment]
Fixed in https://github.com/yannh/kubeconform/pull/267  , thanks :)
