### ISSUE TITLE
The version is `development` if you install `kubeconform` by running the `go install` command.

### ISSUE THREAD

**Issue by kevin85421** [yannh/kubeconform#290]
Reproduce
  ```sh
  go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.7
  kubeconform -v # "development"
  ``` 
  * root cause: https://github.com/yannh/kubeconform/blob/v0.6.7/cmd/kubeconform/main.go#L18

If I download the binary from the release page (https://github.com/yannh/kubeconform/releases/tag/v0.6.7), the version is v0.6.7.

**Comment by yannh** [comment]
That would be working as expected. Builds on a specific tag in our CI pass [ -X main.version={{.Tag}}  ](https://github.com/yannh/kubeconform/blob/1bd44986dd3d281725afab6b173770ec86b454fc/.goreleaser.yml#L24)  to set the version correctly - if you check out and build at a specific tag you should be able to pass this as well. I hope this works for you!

**Comment by yannh** [comment]
I'm hoping this worked! :+1:
