### ISSUE TITLE
Default Kubernetes schema repo is unmaintained?

### ISSUE THREAD

**Issue by Niksko** [yannh/kubeconform#31]
Hi, partly question, partly an issue.

There are reports over at https://github.com/instrumenta/kubernetes-json-schema that the repo is unmaintained. Apparently PRs for K8s 1.19 and 1.20 haven't been merged.

A partial workaround is to use schemas in this repo: https://github.com/awslabs/cdk8s/tree/master/kubernetes-schemas/. However these seem aligned to EKS versions, so there's no 1.20 yet.

Is there a better default location that we can use for up to date schemas?

**Comment by yannh** [comment]
Well this is a problem indeed :( https://github.com/awslabs/cdk8s/tree/master/kubernetes-schemas/  is not the same format. I would love to see this resolved. If this does not however, I would fork kubernetes-json-schema - and if possible try to automate its updates using Github Actions.

**Comment by yannh** [comment]
I'll be maintaining a fork at  https://github.com/yannh/kubernetes-json-schema
I ll do some work on it in the next few weeks, and unless something changes in the parent repository, will update kubeconform's documentation when done.

**Comment by yannh** [comment]
I have updated kubeconform to use the forked schema registry by default. That registry has improved tooling and schemas for all recent versions of kubernetes.
