### ISSUE TITLE
Feature Request: Publish a GitHub Action

### ISSUE THREAD

**Issue by jalseth** [yannh/kubeconform#33]
Hi, thanks for the project and for picking up the work of maintaining the schema updates for newer versions of Kubernetes.

It would be nice if you published a GitHub Action to make it easier to use in GitHub's CI system. If you publish Docker images for each release, it should be pretty straightforward to set up.

**Comment by yannh** [comment]
Hi @jalseth , yes I like the idea :) Would love to publish docker images for each release, though while Github actions requires a PAT instead of a GITHUB_TOKEN I'm not sure I'm ready to do that from CI (see https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions )

**Comment by jalseth** [comment]
That is true for GitHub Container registry, which is separate from GitHub Packages. You can still push to GitHub Packages with `GITHUB_TOKEN`, and then the action should be able to pull from that (I haven't tested this part). The page you linked has an example of pushing to GitHub Packages with the `GITHUB_TOKEN`.

**Comment by yannh** [comment]
Yeah I think you re right, maybe we can rely on Github packages for now, and by the time it gets retired hopefully Github Container Registry will support a GITHUB_TOKEN :) Checking this out now.

**Comment by yannh** [comment]
Alright, added some jobs to release docker images regularly, hopefully Github wont retire Github packages for Docker images before enabling support for GITHUB_TOKEN in the newer Github Container Registry.

So tags: master (what is in the master branch), latest (latest tag released, assuming we always publish incremental versions) and specific releases. If i manage to figure out how to delete the "ELEASE_VERSION" it might look a bit better :)
https://github.com/yannh/kubeconform/packages/258313/versions

I'll work on the action soon.

**Comment by yannh** [comment]
I have a branch that works (github-action) but the Docker Registry will be a problem. There is no anonymous pull from Github packages and I fail to use the image for a github action. Github Container Registry does support anonymous pull, but requires a PAT... or I could setup a Dockerhub account but that also has quite strong rate limits.. Not too sure what the recommended way is.

**Comment by 0x46616c6b** [comment]
Seems that GitHub don't affected from the rate limiting if I read this correctly https://github.community/t/did-dockerhub-rate-limit-affect-github-action/128158/2

**Comment by yannh** [comment]
https://github.blog/changelog/2021-03-24-packages-container-registry-now-supports-github_token/  :heart:  I'll look into this again very soon.

**Comment by yannh** [comment]
@jalseth WDYT:: https://github.com/yannh/test-kubeconform-action/blob/master/.github/workflows/main.yml ?
It's a "Docker Container Action" https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action  - so it actually builds the container.

I still want to publish a container though, would make it easier to use.

**Comment by yannh** [comment]
Alright I've ended up going a different route - https://github.com/yannh/kubeconform/#usage-as-a-github-action
I believe this should be faster since it won't have to rebuild the image every time (even if some layers might get cached). Bandwidth within Github Actions will hopefully stay free in the future.
