### ISSUE TITLE
package with brew for easy install on Mac

### ISSUE THREAD

**Issue by anuaimi** [yannh/kubeconform#37]
it would be great to be able to install this with `brew install kubeconform`.  It's pretty simple to create the scripts for this and I'd be willing to take a first pass at this.

**Comment by yannh** [comment]
Hi @anuaimi , I am not very familiar with Brew or the MacOS ecosystem, however I would be glad to work with you towards this. Note that we currently use goreleaser to generate builds, it looks like it can do brew packages, is this what you had in mind? 
https://goreleaser.com/customization/homebrew/

It seems this is what kubeval is doing: https://github.com/instrumenta/kubeval/blob/529b532b1ea1ea002b1362640c0d52edcc02fc57/.goreleaser.yml#L27-L35
I removed that part because I did not understand it :man_shrugging: :cry:

**Comment by anuaimi** [comment]
yes it is.    The benefit to mac users is that a) the install is easier and b) if brew installs the binary, its trusted. Right now users have to download the binary, move it to `/usr/local/bin` and then use Finder to find the binary and tell MacOS that it is trusted. Doable but ackward.

Here are the steps to setup brew for your binary...

the basic idea is that you create a new repo called `homebrew-yannh`.  In that repo you put the brew install script, which is written in ruby and pretty short.  The script bascially points to the current release in github and has the associated SHA so brew can validate the download.  You can see what kubeval does here https://github.com/instrumenta/homebrew-instrumenta/blob/master/Formula/kubeval.rb. Note, when you do major new releases, you will update the script to point to the new release binary.   

This is what a user will have to do to install kubeconform

```
brew tap yannh/yannh
brew install kubeconform
```

also, to get the latest they just need to do

```
brew upgrade kubconform
```

If you can create the repo, I'm happy to create a pull request with the ruby script.

**Comment by anuaimi** [comment]
btw, have not heard of goreleaser.  Looks great so will need to checkout and possibly use in my go projects.

**Comment by anuaimi** [comment]
I've been playing around with `goreleaser` on one of my own projects.  I converted a custom brew script to one that was generated by `goreleaser`.  

Below is a 1st cut of what I believe needs to be added to the `kubeconform` `goreleaser.yml` file.  This will generate a brew file in the `dist` directory named `kubeconform.rb` but not yet automatically upload it to github.

```
brews:
  - 
    tap:
      owner: yannh
      name: homebrew-yannh
    description: "bla bla bla"    
    license: "Apache 2.0"
    skip_upload: true
```

**Comment by anuaimi** [comment]
@yannh once you are comfortable things are working, you can set `skip_upload` to `false` and the `homebrew-yannh` repo will be updated at the same time as the release is added to `kubeconform`. 

btw, I'm pretty happy with `goreleaser` and surprised I've never heard of it before.

**Comment by chenrui333** [comment]
@anuaimi Now you should be able to run `brew install kubeconform` to install the tool.

**Comment by Hongbo-Miao** [comment]
Just tested, `brew install kubeconform` works for me. Thanks!
