### ISSUE TITLE
no need to create Darwin-386 release binary

### ISSUE THREAD

**Issue by anuaimi** [yannh/kubeconform#38]
The current release has a binary for Darwin-386.  MacOs has never supported 386 CPUs so this is not necessary.  

This can be fixed by added the following to the `.goreleaser.yml` file

```
    ignore:
      - goos: darwin
        goarch: 386
```

**Comment by anuaimi** [comment]
I think the issue is just that an older version of `goreleaser` is being used.  I forked the repo, built things and I ended up with `darwin_amd64` and `darwin_arm64` which is what it should be.

I believe Mac M1 support was added in version 0.157.0.  @yannh can you check what version you build with.

**Comment by yannh** [comment]
Closing because of https://github.com/yannh/kubeconform/pull/52
