### ISSUE TITLE
no binary for new M1 MacBooks

### ISSUE THREAD

**Issue by anuaimi** [yannh/kubeconform#39]
New Macbooks are based on Apple's M1 ARM CPU.   Kubeconform releases should generate a binary for this platform.  goreleaser has support for this as I installed a new binary today (v 0.157.0) and got these by default on my own personal go project.  I'm not sure why they are not being generated for kubeconform.

**Comment by anuaimi** [comment]
I believe this issue is related to #38 and that once `goreleaser` is updated, this issue will also be solved.

**Comment by yannh** [comment]
I understand brew installs from source? @anuaimi could you let me know if brew install kubeconform works for you on a M1 mac?

**Comment by yannh** [comment]
Ok I'm told this works when installing from brew... Might update goreleaser at some point too, but that should solve it for now :)
