### ISSUE TITLE
kubeconform -h fails

### ISSUE THREAD

**Issue by labianchin** [yannh/kubeconform#43]
First, thank you for this great project! It is so great to get k8s resources validations fast and with a short output.

---

On 0.4.3, `kubeconform -h` worked just fine. Now on 0.4.5, one has to supply a file:

On 0.4.3, process exit with code 0:

```
$ /kubeconform -h
Usage: kubeconform [OPTION]... [FILE OR FOLDER]...
  -cache string
        cache schemas downloaded via HTTP to this folder
[...]
```

On 0.4.5, it fails with exit code 1:

```
$ kubeconform -h
Usage: kubeconform [OPTION]... [FILE OR FOLDER]...
  -cache string
[...]
2021/03/08 15:29:13 failing to read data from stdin
```

So far, I found a workaround by using `kubeconform -h /dev/null`.

---

The context on why using `kubconform -h` is to install in a docker image and check that the binary executes properly:

```Dockerfile
RUN set -ex \
    && curl -fsSLO --compressed https://github.com/yannh/kubeconform/releases/download/v0.4.5/kubeconform-linux-amd64.tar.gz \
    && echo "f849385451ec54529a1dc90c4b87969760dd50e74e09c55e126278c9b6c7fccb kubeconform-linux-amd64.tar.gz" | sha256sum -c - \
    && tar -xzf "kubeconform-linux-amd64.tar.gz" -C /usr/local/bin \
    && kubeconform -h /dev/null \
    && rm "kubeconform-linux-amd64.tar.gz"
```

**Comment by yannh** [comment]
I just pushed a hotfix, and added a regression test for this :) Thanks for the quick heads up, try out v0.4.6!
