### ISSUE TITLE
Validation of resources using kustomize

### ISSUE THREAD

**Issue by MaxRink** [yannh/kubeconform#46]
We curently have folders which contain kustomize overlays.
```
dev/kustomization.yaml - failed validation: error while parsing: missing 'kind' key
dev/notification-controller_flux-system.yaml - Deployment notification-controller is invalid: For field spec: selector is required - For field spec.template.spec: containers is required
```
As you can see validation of those resources fails and ignoring based on regex isnt really possible, as i would need the regex feature to work conditionally (e.g. only exclude .yaml when a kustomize.yaml ist present in the folder)

**Comment by yannh** [comment]
Hi @MaxRink , it's not impossible but I think it does fall outside of the scope of this project. Maybe you can bash-fu your way out of this? Some find | xargs combo?
