### ISSUE TITLE
Using multiple schemas on disk with different Kubernetes resources

### ISSUE THREAD

**Issue by TheShahin** [yannh/kubeconform#50]
Our CI/CD-pipeline uses kubeconform to validate Kubernetes resources and today some builds failed due to a temporary outage in GitHub's CDN. To avoid this in the future we downloaded the schemas that we need and point kubeconform to them locally. However, it seems kubeconform is not then able to resolve which schemas to apply to which resources.

For example, I have a directory called `schemas`, which contains the files [service.json](https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.19.8-standalone-strict/service.json) and [deployment-apps-v1.json](https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.19.8-standalone-strict/deployment-apps-v1.json), and a directory called `resources`, which contains the files `service.yaml` and `deployment.yaml`.

Now, when I run
```bash
kubeconform \
  -kubernetes-version 1.19.8 \
  -schema-location ./schemas/service.json \
  -schema-location ./schemas/deployment-apps-v1.json \
  -strict \
  ./resources/
```
I'm given the following error:
```bash
resources/deployment.yaml - Deployment foobar is invalid: For field spec: Additional property replicas is not allowed - For field spec: Additional property template is not allowed - For field spec.selector.matchLabels: Invalid type. Expected: [string,null], given: object
```

It seems like kubeconform is applying the validation schema  `./schemas/service.json` on `./resources/deployment.yaml`.

My current solution, which I am not happy with, is to execute kubeconform once per schema and Kubernetes resource. I would prefer if kubeconform understood, when using local schemas, that it should only apply schemas to their corresponding resources.

Also would be great if `-schema-location` could accept a directory of schemas.

I'm running version v0.4.7.

**Comment by yannh** [comment]
Hi @TheShahin , it does, but it is a templated field: try 

-schema-location 'schemas//{{ .ResourceKind }}{{ .KindSuffix }}.json'

Using a local cache of files is a common occurence though, maybe I should better document that in the Readme.

**Comment by TheShahin** [comment]
Ah, of course, stupid me. Thank you for your help and thank you for a great tool!
