### ISSUE TITLE
 Ingress ingress-service failed validation: could not find schema for Ingress

### ISSUE THREAD

**Issue by Hongbo-Miao** [yannh/kubeconform#58]
Came from https://github.com/instrumenta/kubeval/issues/301 because I got the same issue there 😅

Then I found **kubeconform**!

I have a file `hm-ingress.yaml`:

```shell
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hm-ingress
  namespace: hm
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
```

Currently when I use **kubeconform** to validate it, I got error

>  Ingress hm-ingress failed validation: could not find schema for Ingress

Any idea? Thanks!

**Comment by yannh** [comment]
There is a schema for ingress https://github.com/yannh/kubernetes-json-schema/blob/master/v1.21.2-standalone/ingress.json  :) 
Could you share the command line you are using?

**Comment by Hongbo-Miao** [comment]
Oh simply `kubeconform hm-ingress.yaml`
![image](https://user-images.githubusercontent.com/3375461/124756598-32acba80-df5f-11eb-9af7-531447427c5d.png)

**Comment by knutgoetz** [comment]
Kubeconform uses `1.18.0` as its default k8s version, and i believe the `apiVersion` was `networking.k8s.io/v1beta`  for ingress resources back then. `kubeconform  -kubernetes-version=1.19.0 hm-ingress.yaml` or using any version `>=1.19.0` should work.

**Comment by Hongbo-Miao** [comment]
I think it makes sense to always use latest unless people need use old version to pin to the old one.
And currently latest version is `1.21.0` already. 😀

**Comment by Hongbo-Miao** [comment]
Created the feature request at https://github.com/yannh/kubeconform/issues/59
This can be closed as the issue has been found. Thank you @knutgoetz and @yannh help!
