### ISSUE TITLE
Use latest Kubernetes version by default

### ISSUE THREAD

**Issue by Hongbo-Miao** [yannh/kubeconform#59]
Follow up https://github.com/yannh/kubeconform/issues/58

Kubeconform currently uses `1.18.0` as default Kubernetes version.
It would be great to use latest unless people need use old version. In that case, people can use `-kubernetes-version` to use the old version.
And currently latest version is `1.21.0` already. 😀

**Comment by yannh** [comment]
"master" is the master branchof Kubernetes and is the.. "latest", potentially unreleased. I would suggest using that by default, wdyt?

**Comment by Hongbo-Miao** [comment]
Oh I see. Or maybe a feature request like adding a `-kubernetes-version=latest` if Kubeconform is able to connect the internet?
For this case, either someone hardset each time when there is a new version on this repo, or find an automated way.

**Comment by yannh** [comment]
@Hongbo-Miao opened a PR, let me know what you think!

Note that you can already use -kubernetes-version master  :+1:  It's not the "latest" version, but literally the master branch from https://github.com/kubernetes/kubernetes .

**Comment by Hongbo-Miao** [comment]
Thanks @yannh ! Looks good!

**Comment by yannh** [comment]
Merged :) I'll cut a release soon, there are a few other patches that might make it in.
