### ISSUE TITLE
Is there a Docker way to use?

### ISSUE THREAD

**Issue by Hongbo-Miao** [yannh/kubeconform#60]
I saw currently kubeconform provides a way to use in GitHub Actions.

I am wondering is there a Docker way to use so that I can use in other CI?

For example, kubeval provides a Docker way to use at the bottom of https://www.kubeval.com/installation/
So when I want to analyze all files under k8s folder, I can do

```shell
docker run --rm --volume `pwd`/k8s:/k8s garethr/kubeval k8s/*
```

Thanks!

**Comment by maxbrunet** [comment]
Yes! 

```shell
docker run --rm ghcr.io/yannh/kubeconform:v0.4.8 -h
```

https://github.com/yannh/kubeconform/pkgs/container/kubeconform

**Comment by Hongbo-Miao** [comment]
Oh thanks! I was searching the official one at https://hub.docker.com/
Didn't find the doc about the correct location.

Here is the correct command for future people if want to analyze all yaml files under a `k8s` folder:

```shell
docker run --rm --volume `pwd`/k8s:/k8s ghcr.io/yannh/kubeconform:v0.4.8 k8s/*
```

**Comment by yannh** [comment]
Thanks you were faster :) @Hongbo-Miao I didnt use dockerhub since they now use rate limits... I think ghcr.io does not have rate limits yet? :thinking:  I should update the docs at least to make this more clear. Thanks!
