### ISSUE TITLE
Validation for Kubernetes 19.8 fails for some resources.

### ISSUE THREAD

**Issue by herbaltealeaf** [yannh/kubeconform#66]
This is happening when using the `-kubernetes-version 1.19.8` flag on kubeconform. Looking through the docs this appears to be a problem because the ConfigMap  and VirtualService ( _and possibly a bunch more_ ) resources no longer contain a file named `"{{ .ResourceKind }}-v1.json"`

https://github.com/yannh/kubernetes-json-schema/tree/master/v1.19.8-standalone-strict
![image](https://user-images.githubusercontent.com/41610038/126006760-ea8500f7-2814-45ec-9295-16169ecc57e9.png)

https://github.com/yannh/kubernetes-json-schema/tree/master/v1.18.0-standalone-strict
![image](https://user-images.githubusercontent.com/41610038/126006858-dc06633e-f0e4-459b-87bc-09673eb835e1.png)

Here's an example of an error output from docker-compose:
```
helm-kubeconform_1  | /tmp/helm/test/dev/default/helm/cd950a24.compiled.yml - ConfigMap ihca-carrier-profile-history-es-materializer-configmap-env failed validation: could not find schema for ConfigMap
```

Here's the example 'compiled' helm chart
```
# Source: Helm Chart/templates/configmap-env.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configmap-env
data:
  ENV1: a_value
  ENV2: b_value
  ENV3: c_value
```

Here's the command
```
kubeconform -strict -summary -kubernetes-version 1.19.8 /tmp/helm/test/dev/default/helm/cd950a24.compiled.yml
```
###  Note: 
* This is probably an issue for more than **Just** `1.19.8`
* Validation is successful without the `-kubernetes-version 1.19.8` flag, because it defaults to `1.18.0`.
* This helm chart (which contains other resources such as `Deployment`) is working in k8s 1.19.8.
* Kubeconform will pass, but this is the workaround by removing "{{ .KindSuffix }}" from the location:
  ```
  kubeconform -strict -summary -kubernetes-version 1.19.8 \
  -schema-location default \
  -schema-location "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{ .NormalizedKubernetesVersion }}-standalone{{ .StrictSuffix }}/{{ .ResourceKind }}.json" \
  /tmp/helm/test/dev/default/helm/cd950a24.compiled.yml
  ```

**Comment by yannh** [comment]
Mhhh. Indeed something has changed/is broken here. :thinking:

**Comment by yannh** [comment]
1.19.8 was generated by this PR just before I automated the process, I guess these were generated incorrectly somehow. I deleted the folder and triggered the generate job to re-generate them. It's now fixed. Also, only 1.19.8 was affected :+1:  Thanks for the report!!
