### ISSUE TITLE
Resource validation fails with invalid schema response from http location

### ISSUE THREAD

**Issue by vcardenas** [yannh/kubeconform#67]
When additional http schema locations return a successful (as in 200 status code) response with other than the expected schema, the validation wrongly fails in at least two scenarios (assuming the resource is correct):

1. You add an http location with CRDs and the schema for your resource is not there but you have `-ignore-missing-schemas`
    This should succeed because of the `-ignore-missing-schemas` flag

2. You add 2 (or more) http locations with CRDs and your resource exists in the 2nd location
    This should succeed because the schema does exists in the 2nd location

The issue is due to assuming that a successful http response must be a schema, since it is only possible to add schema locations ending with `json`, which is a fair assumption especially with github hosted content.

When we try a url for a non-existing schema github hosted, we get:
```
curl -v --location https://raw.githubusercontent.com/xeipuuv/gojsonschema/master/testdata/draft7/THIS_DOES_NOT_EXIST.json
> /* IRRELEVANT HTTP REQUEST HEADERS */
> 
< HTTP/1.1 404 Not Found
< Connection: keep-alive
< Content-Length: 14
< /* MORE HTTP RESPONSE HEADERS */
```
The status code response is 404 correctly handled by kubeconform, no issues there.
When we try for a location hosted in bitbucket, we get:
```
curl -v --location https://bitbucket.org/REDACTED/raw/THIS_DOES_NOT_EXIST.json
> /* IRRELEVANT HTTP REQUEST HEADERS */
> 
< HTTP/1.1 302 Found
< /* MORE HTTP RESPONSE HEADERS  */
>
> 
< HTTP/1.1 200 OK
< Content-Type: text/html
< /* MORE HTTP RESPONSE HEADERS  */
```

it is redirecting to a human friendly error page saying that the resource is not there. Because the status code is 200, kubeconform stops looking in the registries and later fails parsing the schema when it is already too late.

Probably this could be fixed by some bitbucket server configuration, but I can see this easily happening with any other server exposing the same behavior and for which you don't have any control.

The issue is in the `downloadSchema` function returning prematurely without validating the schema parsing result:
https://github.com/yannh/kubeconform/blob/f8ffb2f9e3cf0cf1de85535ce670fd2e17838489/pkg/validator/validator.go#L221-L240

I will submit a PR for your consideration to augment the test to reproduce the issue and of course, to fix it.

**Comment by yannh** [comment]
Much appreciated, thank you!
