### ISSUE TITLE
Schemas are ignored

### ISSUE THREAD

**Issue by vovando-pomelo** [yannh/kubeconform#81]
Hello! I've experimenting with the tool and I'm still stuck on how to name the .json files using the suggested format.
Context: I have a manifest that contains the following CRDs:
- security group policy
- virtual service
- external secret

I correctly converted the files using the provided script. The files are externalsecret_v1.json, securitygrouppolicy_v1beta1.json, virtualservice_v1alpha3.json and virtualservice_v1beta1.json
I run kubeconform as follows:
```
kustomize build kubernetes/overlays/dev | kubeconform -schema-location default -schema-location ./Kubernetes/schemas/externalsecret_v1.json -summary -schema-location ./Kubernetes/schemas/virtualservice_v1alpha3.json -schema-location ./Kubernetes/schemas/externalsecret_v1.json
```
and I get the next result:
```
stdin - VirtualService transaction-orchestrator is invalid: For field spec: Must validate at least one schema (anyOf) - For field spec: data is required - For field spec: Must validate one and only one schema (oneOf) - For field spec: Additional property gateways is not allowed - For field spec: Additional property hosts is not allowed - For field spec: Additional property http is not allowed
stdin - SecurityGroupPolicy transaction-orchestrator is invalid: For field spec: Must validate at least one schema (anyOf) - For field spec: data is required - For field spec: Must validate one and only one schema (oneOf) - For field spec: Additional property securityGroups is not allowed - For field spec: Additional property podSelector is not allowed
Summary: 7 resources found parsing stdin - Valid: 5, Invalid: 2, Errors: 0, Skipped: 0
```
It seems it's applying the external secrets schema to virtual service and security group policy. 
Could you help me on this and clarify what's the expected name of the json files in my case?
Thanks!

**Comment by yannh** [comment]
Yes indeed, it is trying to use the wrong schemas! -schema-locations are supposed to be "repositories" not single file, so for the first resource that does not exist in the main kubernetes schema repo (default) it will pick the next schema you pass.

Try   -schema-location ./{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json'

This could likely use some better documentation!

**Comment by vovando-pomelo** [comment]
My bad! Thanks for your answer, it's working now.
And thanks for maintaining this great tool.
