### ISSUE TITLE
Support for "overlapping" Kinds

### ISSUE THREAD

**Issue by tun0** [yannh/kubeconform#84]
Say you have the combination of the following:
```yaml
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
```
and
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
```

Currently these are looked for at `podmonitor-monitoring-v1alpha1.json`  and `podmonitor-monitoring-v1.json` respectively.

If the former were to be promoted to `v1`, they would become indistinguishable from each-other.

Probably the easiest way to solve this is to offer the complete `apiVersion` field as template variable as well? Though this would also require a respective change in `openapi2jsonschema`.

**Comment by yannh** [comment]
Sorry @tun0 a bit late on this one :) Interesting problem, and yes, I believe your suggestion would likely solve this. I'll see when I can get to this improvement :bow:

**Comment by yannh** [comment]
Hi @tun0 , I believe this should have been resolved by https://github.com/yannh/kubeconform/pull/120 !
