### ISSUE TITLE
schema location for more resources

### ISSUE THREAD

**Issue by hadr10** [yannh/kubeconform#85]
Hello,

is it possible to check whole folder with more schema locations for CRDs?
Here is example when i check one helm release and one standard k8s yaml in one folder:
PS C:\tools> .\kubeconform.exe .\ingress.yaml
.\ingress.yaml - HelmRelease nginx failed validation: could not find schema for HelmRelease
PS C:\tools> .\kubeconform.exe -schema-location .\schema\helmrelease_v2beta1.json .\ingress.yaml
PS C:\tools> .\kubeconform.exe -schema-location .\schema\helmrelease_v2beta1.json .\deploy.yaml
.\deploy.yaml - Deployment infra-safe is invalid: For field spec: chart is required - For field spec: interval is required - For field spec: Additional property selector is not allowed - For field spec: Additional property template is not allowed - For field spec: Additional property replicas is not allowed
PS C:\tools> .\kubeconform.exe .\deploy.yaml

I want to put kubeconform to our CI pipeline to check our manifests, but i don't want to get false positive alerts which they block our pipeline.

Thank you

**Comment by yannh** [comment]
I think you are doing the same error as https://github.com/yannh/kubeconform/issues/81 , I really need to improve the documentation on that part :( Can you try the suggested solution in that thread? Thanks!

**Comment by hadr10** [comment]
Thank you, now it works.
PS C:\tools> .\kubeconform.exe -schema-location default -schema-location '.\schema\{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' .\ingress.yaml
PS C:\tools>

Better documentation will help ;)
