### ISSUE TITLE
Directory Support for Local Schema Location

### ISSUE THREAD

**Issue by shin-go** [yannh/kubeconform#93]
Using the Open API to JSON utility script provided, I've pulled down the schemas for all the relevant third party CRDs my org uses in our K8S clusters. The `-schema-location` option can be used multiple times, but for multiple JSON schema files it becomes a bit unwieldy if YAML files containing mixed resources and CRDs is validated against.

Ideally the `-schema-location` option would support being pointed to a directory rather than expect a single JSON file per usage where it would pick up any JSON files located therein.

As an example, I have a YAML file which contains an Ingress, Service, SealedSecret (bitnami sealed-secrets), and Receiver (fluxcd). In order to validate this particular file I'd need to do something like `kubeconform -summary -verbose -schema-location default -schema-location path/to/sealedsecret.json -schema-location path/to/flux/receiver.json foo.yaml`. A simpler approach would be to have a directory locally - call it `crds/` containing the respective JSON schemas. Then I could do something like `kubeconform -summary -verbose -schema-location default -schema-location path/to/crds foo.yaml` and not concern myself with the name of a particular CRD's JSON schema.

As an exercise for giggles, I tried feeding in a large number of CRD JSON files doing something like `export SCHEMAS="" ; for FILE in *; do SCHEMAS="$SCHEMAS -schema-location $FILE"; done && kubeconform -summary -verbose -schema-location default $SCHEMAS foo.yaml`. The result was "file name too long", so there is a limit to how much you can try to feed to it with multiple/many `-schema-location` flags.

**Comment by yannh** [comment]
Hi @shin-go , I believe you are mis-using the -schema-location parameter, you are not the first one, and that really points to poor documentation on my part :( Please check out [this answer](https://github.com/yannh/kubeconform/issues/81) , that should help you do what you are trying to achieve!

**Comment by shin-go** [comment]
I gave that link a read and it's a different use case from what I (tried) to describe originally. In that particular user's case, they knew ahead of time what CRDs were in the YAML file attempting to validate. In my use case, I intend to integrate kubeconform in a validation CICD pipeline - I have no ability to guess what developers may put into their YAML files.

So unless I implement some pre-validation logic to scan what YAML files have changed and look for things like `kind: <something>` and `apiVersion: <version>`, trying to use the suggested `-schema-location './{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json'` wouldn't work. Without digging into the codebase, I was presuming that when you use the `-schema-location` flag, the JSON file(s) passed in were being read to find a match for an encountered resource kind and apiVersion.

Let me know if I'm still misinterpreting the recommendation made on that other issue!

**Comment by eyarz** [comment]
Just to clarify, `ResourceKind` and `ResourceAPIVersion` are parameters, not place-holders.
Therefore, you don't need to pass the `kind` and `apiVersion`, they will be pulled by Kubecoform.
This is a similar concept to how Kubeconform pulls schemas from [this repo](https://github.com/yannh/kubernetes-json-schema/).

Maybe [this video](https://hub.datree.io/schema-validation#ju-how-to-pull-your-crds-schemas-to-validate-your-manifests) will help you understand how it is implemented. It shows another tool but under the hood, it's Kubeconform so it will work the same :)

**Comment by shin-go** [comment]
Ahhhhhh yes, that makes sense now. Thanks for your patience! One thing I did notice that the Python script seems to accept, but kubeconform parameters don't is the use of `{group}` when building the JSON schemas. kubeconform reports the following when trying to use group as `{{ .Group }}`:

```
failed initialising schema location registry: template: tpl:1:3: executing "tpl" at <.Group>: can't evaluate field Group in type struct { NormalizedKubernetesVersion string; StrictSuffix string; ResourceKind string; ResourceAPIVersion string; KindSuffix string }
```
Looking at the [registry.go](https://github.com/yannh/kubeconform/blob/f8ffb2f9e3cf0cf1de85535ce670fd2e17838489/pkg/registry/registry.go#L59) struct, Group doesn't seem to be anticipated unless it's used as like `{{ .StrictSuffix }}`?

Other than that, this works. Thanks again!

**Comment by chuegel** [comment]
I'm also struggling including locally stored schemas with kubeconform.
So how exactly should the option `-schema-location` be used? 
I'm trying to validate flux CRDs but this doesn't seem to work:
`kubeconform -schema-location default  -schema-location '/tmp/flux-crd-schemas/master-standalone-strict/{{ .ResourceKind }}-{{ .KindSuffix }}-{{ .ResourceAPIVersion }}.json' ./clusters/lab/ `

schema files:
```
alert-notification-v1beta1.json
bucket-source-v1beta1.json
gitrepository-source-v1beta1.json
helmchart-source-v1beta1.json
helmrelease-helm-v2beta1.json
helmrepository-source-v1beta1.json
imagepolicy-image-v1alpha1.json
imagepolicy-image-v1alpha2.json
imagepolicy-image-v1beta1.json
imagerepository-image-v1alpha1.json
imagerepository-image-v1alpha2.json
imagerepository-image-v1beta1.json
imageupdateautomation-image-v1alpha1.json
imageupdateautomation-image-v1alpha2.json
imageupdateautomation-image-v1beta1.json
kustomization-kustomize-v1beta1.json
kustomization-kustomize-v1beta2.json
provider-notification-v1beta1.json
receiver-notification-v1beta1.json
```
I'm confused

**Comment by shin-go** [comment]
@chuegel The way I got it working was to use the python script to create the CRD schemas and saving the resulting json file(s) exporting the expected env as `export FILENAME_FORMAT='{kind}_{version}'`. Your case might be different, but I was originally having the CRD schema format as `{group}_{kind}_{version}`, which didn't seem to be expected by kubeform using the interpolation notation documented. I don't think using underscore versus dash for delimiting is a factor (but maybe try it for giggles).

Ultimately what I run that works is something like `kubeconform -summary -ignore-missing-schemas -schema-location default -schema-location './schemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' -kubernetes-version <version> .`

**Comment by hazim1093** [comment]
@chuegel I got it to work with @shin-go 's trick 

I renamed all files using the following shell script
```
for file in *.json; do
    new_name=$(echo "${file}" | sed 's/-.*-/-/')
    mv $file $new_name
done
```

and also had to provide the schema for CRDs (from https://github.com/yannh/kubeconform/issues/51#issuecomment-1002639168)

```
kubeconform -summary -schema-location default -schema-location './schemas/{{ .ResourceKind }}-{{ .ResourceAPIVersion }}.json' -schema-location apis__apiextensions.k8s.io__v1_openapi.json ./kustomize_out
```

**Comment by chuegel** [comment]
@hazim1093 yes, including `-schema-location https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__apiextensions.k8s.io__v1_openapi.json`worked.
Thank you

**Comment by yannh** [comment]
Looks like this got solved in the end... If you feel the documentation could be made better on that -schema-location parameter please contribute this is a common pitfall :pray:

**Comment by gregawoods** [comment]
@shin-go 

> The way I got it working was to use the python script to create the CRD schemas and saving the resulting json file(s) exporting the expected env as `export FILENAME_FORMAT='{kind}_{version}'`. Your case might be different, but I was originally having the CRD schema format as `{group}_{kind}_{version}`, which didn't seem to be expected by kubeform using the interpolation notation documented. I don't think using underscore versus dash for delimiting is a factor (but maybe try it for giggles).

Can I ask where people are finding the flux openapi schema to run the python script against? I think I understand that the python script is used to create CRD files, which I then pass into kubeconform to consume. But I haven't had any luck locating the Open API source for flux.
