### ISSUE TITLE
Resources with missing schemas not ignored

### ISSUE THREAD

**Issue by seif-raafat** [yannh/kubeconform#94]
Hi!

I'm seeing some issues with `-ignore-missing-schemas` when supplying a JSON schema file ending with .json. There will be many custom resources that we need to be ignored, and listing them under the `-skip` flag would make it painful to maintain. 

```
$ kubeconform -ignore-missing-schemas -schema-location default -schema-location "https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json" app.yaml
 
app.yaml - VaultSecret sample-secret is invalid: For field (root): Must validate one and only one schema (oneOf) - For field apiVersion: apiVersion does not match: "argoproj.io/v1alpha1" - For field kind: kind does not match: "ClusterWorkflowTemplate"
```

Expected behavior: ignore resources where schemas could not be found.

**Comment by yannh** [comment]
Hi @seif-raafat ! Unfortunately  you are not correctly using -schema-location, and this being a common occurrence among users points to either a confusing parameter on my part or poor documentation :(

Could you check if this answer helps you out: https://github.com/yannh/kubeconform/issues/81 ? 
All the best!

**Comment by seif-raafat** [comment]
Thank you, it is working as intended now after making the suggested adjustments. I think the documentation is good, I just didn't read it correctly. Great work on the product!
