### ISSUE TITLE
Can I use kubeconform hero image in my blog article?

### ISSUE THREAD

**Issue by lirlia** [yannh/kubeconform#95]
Hi @yannh !

![image](https://user-images.githubusercontent.com/10017674/152477818-b8655fe3-e9ff-47bf-b218-36c16a846f2d.png)

I want to introduce [asdf-kubeconform](https://github.com/lirlia/asdf-kubeconform) in my blog, and use this nice hero image.
Could you tell me License policy to use this image?

**Comment by yannh** [comment]
Hi @lirlia ! This image has been contributed by @eyarz  under the licence of this repository, which is Apache v2 - this website explains well the conditions: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

 I hope this helps!

**Comment by lirlia** [comment]
@yannh 

Thanks! I understood!
