### ISSUE TITLE
Validating SOPS encrypted secret

### ISSUE THREAD

**Issue by tomhuang12** [yannh/kubeconform#98]
I am using fluxv2 and following their [multi-tenancy](https://github.com/fluxcd/flux2-multi-tenancy) example which has a [script](https://github.com/fluxcd/flux2-multi-tenancy/blob/main/scripts/validate.sh) that uses `kubeconform` to validate files. I am also using [Mozilla SOPS](https://fluxcd.io/docs/guides/mozilla-sops/) to encrypt secrets to store in git. sops will add a additional field `sops` to the secret which is not conforming with the `v1/Secret` API spec which fails the validation with `Additional property sops is not allowed`. A few possible solutions I could do:
- remove `-strict` flag but it won't be able to catch potential legitimate issues
- move sops encrypted secrets somewhere that's not being validated by kubeconform
- create my own `v1/Secrets` json schema but then I won't be able to use the default schema for the other default k8s schemas since mine won't able to override what's provided in default, thus I need to maintain all the schemas to have a custom `v1/Secret`.

Any of the above is a workaround to be able to get my test pass. Any suggestions on a better solution? Thanks for the great tool!

**Comment by yannh** [comment]
Hi @tomhuang12 ! you could patch the json schema for secrets, and use -schema-location to add that additional schema? that would ensure those are validated too. If you only need one additional optional field it shouldn't be too hard to patch manually? 🤔 
Do note -schema-location needs to be a templated string, refer to the docs, several people have had issues using that correctly. Best of luck!

**Comment by tomhuang12** [comment]
Thanks for responding. Yes that's the first thing I've tried which is my third bullet point but it won't override the default `v1/Secret` schema is I use it in combination with `default`. Here is the example:

Command
```
cat sops-secret.yaml | kubeconform -strict -ignore-missing-schemas -schema-location default -schema-location /tmp/schema
```

sops-secret.yaml
<details>
apiVersion: v1
kind: Secret
metadata:
    name: test
    namespace: default
stringData:
    password: xyz
    username: abc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-01T00:00:00Z"
    mac: abc
    pgp:
        - created_at: "2022-01-01T00:00:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            example
            -----END PGP MESSAGE-----
          fp: abc
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
</details>

/tmp/schema/secret-v1.json
<details>
{
    "description": "Secret holds secret data of a certain type. The total bytes of the values in the Data field must be less than MaxSecretSize bytes.",
    "properties": {
      "apiVersion": {
        "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
        "type": [
          "string",
          "null"
        ],
        "enum": [
          "v1"
        ]
      },
      "data": {
        "additionalProperties": {
          "format": "byte",
          "type": [
            "string",
            "null"
          ]
        },
        "description": "Data contains the secret data. Each key must consist of alphanumeric characters, '-', '_' or '.'. The serialized form of the secret data is a base64 encoded string, representing the arbitrary (possibly non-string) data value here. Described in https://tools.ietf.org/html/rfc4648#section-4",
        "type": [
          "object",
          "null"
        ]
      },
      "immutable": {
        "description": "Immutable, if set to true, ensures that data stored in the Secret cannot be updated (only object metadata can be modified). If not set to true, the field can be modified at any time. Defaulted to nil.",
        "type": [
          "boolean",
          "null"
        ]
      },
      "kind": {
        "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
        "type": [
          "string",
          "null"
        ],
        "enum": [
          "Secret"
        ]
      },
      "metadata": {
        "$ref": "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta",
        "description": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
      },
      "stringData": {
        "additionalProperties": {
          "type": [
            "string",
            "null"
          ]
        },
        "description": "stringData allows specifying non-binary secret data in string form. It is provided as a write-only input field for convenience. All keys and values are merged into the data field on write, overwriting any existing values. The stringData field is never output when reading from the API.",
        "type": [
          "object",
          "null"
        ]
      },
      "type": {
        "description": "Used to facilitate programmatic handling of secret data. More info: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types",
        "type": [
          "string",
          "null"
        ]
      },
      "sops": {
        "additionalProperties": {
          "type": [
            "string",
            "array",
            "null"
          ]
        },
        "description": "sops field.",
        "type": [
          "object",
          "null"
        ]
      },
    },
    "type": "object",
    "x-kubernetes-group-version-kind": [
      {
        "group": "",
        "kind": "Secret",
        "version": "v1"
      }
    ],
    "$schema": "http://json-schema.org/schema#"
  }
</details>

**Comment by yannh** [comment]
So a note, and I understand the doc might not be perfect - the schemas repositories are searched in the order they are given, so you would need to pass your local folder first, otherwise it will pick the secret definition from the default registry if it finds it. Then, -schema-location  needs to be a templated string, so something like:

cat sops-secret.yaml | kubeconform -strict -ignore-missing-schemas -schema-location '/tmp/schema/{{ .ResourceKind }}-{{ .ResourceAPIVersion }}.json' -schema-location default 

Good luck!

**Comment by chuegel** [comment]
Here is a script which gets triggered by a CI pipeline. It is also based on the script you linked above.
It validates all flux resources successful:
```bash

#!/bin/bash
# find our local path to run in CI
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
export PATH=$PATH:$SCRIPTPATH

# mirror kustomize-controller build options
kustomize_flags="--load-restrictor=LoadRestrictionsNone --reorder=legacy"
kustomize_config="kustomization.yaml"

# Kubernetes Open API extension scheme
OPENAPI=https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__apiextensions.k8s.io__v1_openapi.json

# loop kubeconform trough these folders
resources=('apps' 'infrastructure')

# reliable set and interpret exit codes
set -o errexit

echo "INFO - Downloading Flux OpenAPI schemas"
mkdir -p /tmp/flux-crd-schemas/master-standalone-strict
curl -sL https://github.com/fluxcd/flux2/releases/latest/download/crd-schemas.tar.gz | tar zxf - -C /tmp/flux-crd-schemas/master-standalone-strict


find . -type f -name '*.yaml' -print0 | while IFS= read -r -d $'\0' file;
  do
    echo "INFO - Validating $file"
    yq e 'true' "$file" > /dev/null
done

echo "INFO - Validating clusters"
         kubeconform  -exit-on-error -verbose -summary -schema-location default  -schema-location '/tmp/flux-crd-schemas/master-standalone-strict/{{ .ResourceKind }}{{ .KindSuffix }}.json' -schema-location $OPENAPI ./clusters/


for k8s_resources in "${resources[@]}"
do
 echo "INFO - Validating kustomize overlays"
 find ./$k8s_resources -type f -name $kustomize_config -print0 | while IFS= read -r -d $'\0' file;
  do
    echo "INFO - Validating kustomization ${file/%$kustomize_config}"
    kustomize build "${file/%$kustomize_config}" $kustomize_flags  | kubeconform -exit-on-error  -verbose -summary -schema-location default  -schema-location '/tmp/flux-crd-schemas/master-standalone-strict/{{ .ResourceKind }}{{ .KindSuffix }}.json' -schema-location $OPENAPI
  done
done
```

`stdin - Secret redis-secret is valid`

**Comment by yannh** [comment]
Thanks a lot  @chuegel ! Just a note as mentioned: kubeconform will search the schema registries in the order given as parameter, so it will only look in additional schema locations if it can not find a schema for that resource type/version in the default repository. If you want to override the schema from the default repo, you might need to pass --schema-location default  last! Thanks for jumping in and sharing this script :+1: :100:

**Comment by tomhuang12** [comment]
Understood. Thank you all for this!

**Comment by chuegel** [comment]
@tomhuang12 was right. The additional sops property cannot be validated. I couldn't figure out how to do that right now so I sticked with 'skip=secret'

Anyways, if you want to use a strict validation without skipping missing schemas, here is how we do it in our gitlab pipeline. We use `cert-manager`, `calico`, `istio` CRDs which we convert to json thanks to the handy [script](https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py) provided by @yannh 

```yaml
stages:
- validation

"Manifest validation":
  stage: validation
  tags:
    - dind
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - README.md
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    KUBECONFORM: "https://github.com/yannh/kubeconform/releases/download/v0.4.12/kubeconform-linux-amd64.tar.gz"
    KUSTOMIZE: "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
    YQURL: "https://github.com/mikefarah/yq/releases/download/v4.11.2/yq_linux_amd64"
    OPENAPI2JSON: "https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py"
  before_script:
    - pip install pyyaml pytest
    - curl -L -O $KUBECONFORM && tar xvf kubeconform-linux-amd64.tar.gz
    - chmod 755 kubeconform
    - curl -s "$KUSTOMIZE"  | bash
    - curl -L -o yq "$YQURL" && chmod 755 yq
    - curl -L -o openapi2jsonschema.py "$OPENAPI2JSON" && chmod 755 openapi2jsonschema.py
    - mv kustomize kubeconform yq openapi2jsonschema.py ./scripts
  script:
    - bash ./scripts/validate.sh
```

```bash
#!/bin/bash
# find our local path to run in CI
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
export PATH=$PATH:$SCRIPTPATH

# Kubernetes Open API extension scheme
OPENAPI="https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__apiextensions.k8s.io__v1_openapi.json"
CERTMANAGER_VERSION="v1.7.1"
CERTMANAGER_CRD="https://github.com/cert-manager/cert-manager/releases/download/$CERTMANAGER_VERSION/cert-manager.crds.yaml"
CALICO_CRD="https://projectcalico.docs.tigera.io/manifests/calico.yaml"
ISTIO_CRD="https://raw.githubusercontent.com/istio/istio/master/manifests/charts/base/crds/crd-all.gen.yaml"
SCHEMA_DIR="/tmp/schema"

set -o errexit

echo "INFO - Downloading Flux OpenAPI schemas"
mkdir -p ${SCHEMA_DIR}/flux/master-standalone-strict
curl -sL https://github.com/fluxcd/flux2/releases/latest/download/crd-schemas.tar.gz | tar zxf - -C ${SCHEMA_DIR}/flux/master-standalone-strict

echo "INFO - Downloading cert-manager OpenAPI schemas"
mkdir -p ${SCHEMA_DIR}/cert-manager/master-standalone-strict
curl -sL $CERTMANAGER_CRD -o ${SCHEMA_DIR}/cert-manager/master-standalone-strict/cert-manager.crds.yaml

echo "INFO - Convert cert-manager OpenAPI schemas to json"
(cd ${SCHEMA_DIR}/cert-manager/master-standalone-strict && openapi2jsonschema.py cert-manager.crds.yaml)

echo "INFO - Downloading calico OpenAPI schemas"
mkdir -p ${SCHEMA_DIR}/calico/master-standalone-strict
curl -sL $CALICO_CRD -o ${SCHEMA_DIR}/calico/master-standalone-strict/calico.crds.yaml

echo "INFO - Convert calico OpenAPI schemas to json"
(cd ${SCHEMA_DIR}/calico/master-standalone-strict && openapi2jsonschema.py calico.crds.yaml)

echo "INFO - Downloading istio OpenAPI schemas"
mkdir -p ${SCHEMA_DIR}/istio/master-standalone-strict
curl -sL $ISTIO_CRD -o ${SCHEMA_DIR}/istio/master-standalone-strict/istio.crds.yaml

echo "INFO - Convert OpenAPI schemas to json"
(cd ${SCHEMA_DIR}/istio/master-standalone-strict && openapi2jsonschema.py istio.crds.yaml)

find . -type f -name '*.yaml' -print0 | while IFS= read -r -d $'\0' file;
  do
    echo "INFO - Validating file $file"
    yq e 'true' "$file" > /dev/null
done

kubeconform_config=(-skip='Secret' -strict -schema-location default -schema-location ${OPENAPI} -schema-location ${SCHEMA_DIR}'/flux/master-standalone-strict/{{ .ResourceKind }}{{ .KindSuffix }}.json'  -schema-location ${SCHEMA_DIR}'/cert-manager/master-standalone-strict/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' -schema-location ${SCHEMA_DIR}'/calico/master-standalone-strict/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' -schema-location ${SCHEMA_DIR}'/istio/master-standalone-strict/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' -verbose -summary)

echo "INFO - Validating clusters"
find ./clusters -type f -name '*.yaml' -print0 | while IFS= read -r -d $'\0' file;
  do
    kubeconform "${kubeconform_config[@]}" ${file}
    if [[ ${PIPESTATUS[0]} != 0 ]]; then
      exit 1
    fi
done

# mirror kustomize-controller build options
kustomize_flags="--load-restrictor=LoadRestrictionsNone --reorder=legacy"
kustomize_config="kustomization.yaml"

echo "INFO - Validating kustomize overlays"
find . -maxdepth 3 -type f -name $kustomize_config -print0 | while IFS= read -r -d $'\0' file;
  do
    echo "INFO - Validating kustomization ${file/%$kustomize_config}"
    kustomize build "${file/%$kustomize_config}" $kustomize_flags | \
      kubeconform  "${kubeconform_config[@]}"
    if [[ ${PIPESTATUS[0]} != 0 ]]; then
      exit 1
    fi
done
```

**Comment by sc-joostvandencruyce** [comment]
I used this workaround to strip the sops part: 
`cat "${file}" | yq "del(.sops)" | kubeconform "${kubeconform_config[@]}"`

and

`kustomize build "${file/%$kustomize_config}" "${kustomize_flags[@]}" | \
    yq "del(.sops)" | \
    kubeconform "${kubeconform_config[@]}"`
