### ISSUE TITLE
SARIF output ? :)

### ISSUE THREAD

**Issue by nvuillam** [yannh/kubeconform#99]
Most of commonly used linters can now output [SARIF](https://sarifweb.azurewebsites.net/) format

Would it be also possible to have it for kubeconform ?

It would improve a lot its integration in the next version of MegaLinter :)

Note: you can see how it has been managed in golang for revive: https://github.com/mgechev/revive/pull/508/files , using [garif package](https://github.com/chavacava/garif)

Best regards

**Comment by yannh** [comment]
Hi @nvuillam , I have no immediate plans to add SARIF format, honestly it is not something I personnally need. From looking quickly at the spec I am not exactly sure what the output would look like :thinking:  If someone came with a decently-enough tested patch I would likely merge that though :)

**Comment by nvuillam** [comment]
Thanks for your reply, go is not in my stack yet, I hope someone will see this issue and provide a PR :)

**Comment by mridang** [comment]
A bit of an old issue but @yannh I'm happy to provide a small PR if you're okay with this?

**Comment by mridang** [comment]
Just added a pretty thoroughly tested patch.
